package uz.mirix.tracelens.internal;

import uz.mirix.tracelens.TraceCategory; import uz.mirix.tracelens.TraceLensProperties;
import java.lang.reflect.*; import java.sql.*; import java.util.Map; import java.util.Set;

final class JdbcProxyFactory {
    private static final Set<String> EXECUTION_METHODS=Set.of("execute","executeQuery","executeUpdate","executeLargeUpdate","executeBatch","executeLargeBatch"); private JdbcProxyFactory(){}
    static Connection wrapConnection(Connection target,TraceLensProperties properties){ if(Proxy.isProxyClass(target.getClass())){InvocationHandler h=Proxy.getInvocationHandler(target); if(h instanceof ConnectionHandler)return target;} return (Connection)Proxy.newProxyInstance(target.getClass().getClassLoader(),new Class<?>[]{Connection.class},new ConnectionHandler(target,properties)); }
    private static final class ConnectionHandler implements InvocationHandler { private final Connection target; private final TraceLensProperties properties; ConnectionHandler(Connection t,TraceLensProperties p){target=t;properties=p;} public Object invoke(Object proxy,Method method,Object[] args)throws Throwable{ String name=method.getName(); try{Object result=method.invoke(target,args); if(result instanceof PreparedStatement s&&args!=null&&args.length>0&&args[0] instanceof String sql)return wrapStatement(s,sql,properties,(Connection)proxy); if(result instanceof Statement s&&"createStatement".equals(name))return wrapStatement(s,null,properties,(Connection)proxy); return result;}catch(InvocationTargetException ex){throw ex.getTargetException();}} }
    private static Statement wrapStatement(Statement target,String sql,TraceLensProperties p,Connection c){Class<?> api=target instanceof CallableStatement?CallableStatement.class:target instanceof PreparedStatement?PreparedStatement.class:Statement.class; return (Statement)Proxy.newProxyInstance(target.getClass().getClassLoader(),new Class<?>[]{api},new StatementHandler(target,sql,p,c));}
    private static final class StatementHandler implements InvocationHandler { private final Statement target; private final String preparedSql; private final TraceLensProperties properties; private final Connection connectionProxy; StatementHandler(Statement t,String s,TraceLensProperties p,Connection c){target=t;preparedSql=s;properties=p;connectionProxy=c;} public Object invoke(Object proxy,Method method,Object[] args)throws Throwable{if("getConnection".equals(method.getName())&&method.getParameterCount()==0)return connectionProxy; if(!EXECUTION_METHODS.contains(method.getName()))return invokeTarget(method,args); String sql=preparedSql; if(sql==null&&args!=null&&args.length>0&&args[0] instanceof String v)sql=v; TraceContext context=TraceContextHolder.current(); if(context==null)return invokeTarget(method,args); long started=System.nanoTime(); Throwable failure=null; try{return invokeTarget(method,args);}catch(Throwable ex){failure=ex;throw ex;}finally{context.record(TraceCategory.SQL,SqlSanitizer.label(sql,properties.getSql().getMaxLength()),started,System.nanoTime(),failure==null?Map.of():Map.of("error",failure.getClass().getSimpleName()));}} private Object invokeTarget(Method m,Object[] a)throws Throwable{try{return m.invoke(target,a);}catch(InvocationTargetException ex){throw ex.getTargetException();}} }
}
