package uz.mirix.tracelens.internal;

import org.springframework.data.redis.connection.RedisConnection; import uz.mirix.tracelens.TraceCategory;
import java.lang.reflect.*; import java.util.*;
final class RedisProxyFactory {
    private static final Set<String> INFRASTRUCTURE=Set.of("close","isClosed","getNativeConnection","isQueueing","isPipelined","openPipeline","closePipeline","getSentinelConnection"); private RedisProxyFactory(){}
    static RedisConnection wrap(RedisConnection target){return (RedisConnection)proxy(target,interfaces(target.getClass(),RedisConnection.class));}
    private static Object proxy(Object target,Class<?>[] interfaces){return Proxy.newProxyInstance(target.getClass().getClassLoader(),interfaces,new RedisHandler(target));}
    private static final class RedisHandler implements InvocationHandler {private final Object target; RedisHandler(Object t){target=t;} public Object invoke(Object proxy,Method method,Object[] args)throws Throwable{if(isCommandGroupAccessor(method)){Object result=invokeTarget(method,args); if(result!=null&&method.getReturnType().isInterface())return proxy(result,new Class<?>[]{method.getReturnType()});return result;} if(INFRASTRUCTURE.contains(method.getName())||method.getDeclaringClass()==Object.class||method.getName().startsWith("is"))return invokeTarget(method,args); TraceContext context=TraceContextHolder.current(); if(context==null)return invokeTarget(method,args); long started=System.nanoTime();Throwable failure=null;try{return invokeTarget(method,args);}catch(Throwable ex){failure=ex;throw ex;}finally{String op=method.getName().replace("_","").toUpperCase();context.record(TraceCategory.REDIS,"Redis "+op,started,System.nanoTime(),failure==null?Map.of():Map.of("error",failure.getClass().getSimpleName()));}} private Object invokeTarget(Method method,Object[] args)throws Throwable{try{return method.invoke(target,args);}catch(InvocationTargetException ex){throw ex.getTargetException();}}}
    private static boolean isCommandGroupAccessor(Method m){Package pkg=m.getReturnType().getPackage();return m.getParameterCount()==0&&m.getReturnType().isInterface()&&pkg!=null&&pkg.getName().startsWith("org.springframework.data.redis.connection")&&m.getReturnType().getSimpleName().endsWith("Commands");}
    private static Class<?>[] interfaces(Class<?> type,Class<?> required){LinkedHashSet<Class<?>> out=new LinkedHashSet<>();Class<?> c=type;while(c!=null){for(Class<?> candidate:c.getInterfaces())if(Modifier.isPublic(candidate.getModifiers()))out.add(candidate);c=c.getSuperclass();}out.add(required);return out.toArray(Class<?>[]::new);}
}
