package uz.mirix.tracelens.internal;

import uz.mirix.tracelens.TraceCategory; import uz.mirix.tracelens.TraceReport; import uz.mirix.tracelens.TraceSpan;
import java.time.Instant; import java.util.*; import java.util.concurrent.ConcurrentLinkedQueue; import java.util.concurrent.atomic.AtomicInteger;
public final class TraceContext { private final String traceId=UUID.randomUUID().toString().replace("-","").substring(0,16); private final Instant startedAt=Instant.now(); private final long startedNanos=System.nanoTime(); private final String method,initialPath; private final int maxSpans; private final ConcurrentLinkedQueue<TraceSpan> spans=new ConcurrentLinkedQueue<>(); private final AtomicInteger spanCount=new AtomicInteger(); private volatile boolean truncated;
 public TraceContext(String method,String initialPath,int maxSpans){this.method=method;this.initialPath=initialPath;this.maxSpans=maxSpans;} public String traceId(){return traceId;} public long startedNanos(){return startedNanos;}
 public void record(TraceCategory category,String name,long started,long ended,Map<String,String> attrs){if(ended<started)return;if(spanCount.incrementAndGet()>maxSpans){truncated=true;return;}spans.add(new TraceSpan(category,SafeText.singleLine(name,220),Math.max(0,started-startedNanos),ended-started,attrs));}
 public TraceReport finish(String route,int status,Throwable error,long ended){long total=Math.max(0,ended-startedNanos);List<TraceSpan> captured=new ArrayList<>(spans);long application=Math.max(0,total-coveredDuration(captured,total));captured.add(new TraceSpan(TraceCategory.APPLICATION,"application self time",0,application,Map.of()));captured.sort(Comparator.comparing((TraceSpan s)->s.category()==TraceCategory.APPLICATION?0:1).thenComparingLong(TraceSpan::startOffsetNanos));return new TraceReport(traceId,startedAt,method,route==null||route.isBlank()?initialPath:route,status,total,captured,error==null?null:error.getClass().getName(),truncated);}
 private static long coveredDuration(List<TraceSpan> spans,long total){record Interval(long start,long end){} List<Interval> is=spans.stream().filter(s->s.category()!=TraceCategory.APPLICATION).map(s->new Interval(Math.min(total,Math.max(0,s.startOffsetNanos())),Math.min(total,Math.max(0,s.startOffsetNanos()+s.durationNanos())))).filter(i->i.end()>i.start()).sorted(Comparator.comparingLong(Interval::start)).toList();long covered=0,cs=-1,ce=-1;for(Interval i:is){if(cs<0){cs=i.start();ce=i.end();}else if(i.start()<=ce)ce=Math.max(ce,i.end());else{covered+=ce-cs;cs=i.start();ce=i.end();}}if(cs>=0)covered+=ce-cs;return Math.min(total,covered);}
}
